spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 093c6b02713aff09bb20830ea6c5da9b
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname